---
swagger: "2.0"
info:
  version: "2022-07-14T05:00:20Z"
  title: "dev-product-service"
host: "o3lc79zr1i.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /product:
    get:
      responses: {}
  /products:
    get:
      responses: {}
  /products/{productId}:
    get:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        type: "string"
      responses: {}
